# Generated by Django 4.0.6 on 2022-08-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Usuario')], default=2, max_length=1),
        ),
    ]
