# Generated by Django 4.0.6 on 2022-08-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_ingredient_recipe_unitofmeasurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
